version: "3.9"
services:
  api:
    build:
      context: ./BusinessEconomyManager
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
  app:
    build:
      context: ./AppBusinessEconomyManager
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api
