version: "3.4"

services:
    api:
        image: chrisdevguidecontainerregistry.azurecr.io/business-economy-manager
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:80"